# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY *.sln .
COPY MintyOrderApi/*.csproj ./MintyOrderApi/
RUN dotnet restore

# Copy everything else and build
COPY MintyOrderApi/. ./MintyOrderApi/
WORKDIR /src/MintyOrderApi
RUN dotnet publish -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MintyOrderApi.dll"]